LOAD XML LOCAL INFILE '/var/www/html/public/database/Posts.xml' 
INTO TABLE posts
 ROWS IDENTIFIED BY '<row>'
 (
	@`Id`,
    @`PostTypeId`,
    @`AcceptedAnswerId`,
    @`Score`,
    @`ViewCount`,
    @`Body`,
    @`OwnerUserId`,
    @`LastEditorUserId`,
    @`LastEditorDisplayName`,
    @`LastEditDate`,
    @`LastActivityDate`,
    @`Title`,
    @`Tags`,
    @`AnswerCount`,
    @`CommentCount`,
    @`FavoriteCount`,
    @`CommunityOwnedDate`,
    @`ContentLicense`,
    @`ParentId`,
    @`OwnerDisplayName`,
    @`ClosedDate`,
    @`CreationDate`
 )
SET `id` = @`Id`, 
`post_type_id` = @`PostTypeId`, 
`owner_user_id` = @`OwnerUserId`, 
`last_editor_user_id` = @`LastEditorUserId`, 
`accepted_answer_id` = @`AcceptedAnswerId`, 
`score` = @`Score`, 
`parent_id` = @`ParentId`, 
`view_count` = @`ViewCount`, 
`answer_count` = @`AnswerCount`, 
`comment_count` = @`CommentCount`, 
`owner_display_name` = @`OwnerDisplayName`, 
`last_editor_display_name` = @`LastEditorDisplayName`, 
`title` = @`Title`, 
`tags` = @`Tags`, 
`content_license` = @`ContentLicense`, 
`body` = @`Body`, 
`favorite_count` = @`FavoriteCount`, 
`community_owned_date` = @`CommunityOwnedDate`, 
`closed_date` = @`ClosedDate`, 
`last_edit_date` = @`LastEditDate`, 
`last_activity_date` = @`LastActivityDate`, 
 `created_at` = @`CreationDate`, 
 `updated_at` = @`LastEditDate`;